### ISSUE TITLE
Consider breaking out tools into individual repos

### ISSUE THREAD

**Issue by pbnj** [anshumanbh/kubebot#1]
Hey @anshumanbh , I really love this project. Thank you for all the effort you've put into this.

I see a lot of potential for this to be extended/expanded to include more tools and I would love to collaborate with you on this.

I feel like in order to achieve this reliably without breaking the main tool or breaking other tools, we may need to break out the tools directory into separate repos (each tool in its own repo, e.g. `kubebot-nmap`, `kubebot-gitrob`, ...etc).

What do you think?

**Comment by anshumanbh** [comment]
Hey @petermbenjamin , thats awesome to hear! I am really looking forward to making this better and would really appreciate any collaboration I could get. 

Can you walk me through some some advantages of doing it that way? The tools are already kind of separate in the `tools/` directory so what will we achieve if we actually take them out all together and have them in their own repos? I must be missing something obvious here..
